"""tags device status device validation

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-23 20:37:02.114334

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    validation_status_enum = sa.Enum(
        "PENDING", "REACHABLE", "AUTH_FAILED", "UNREACHABLE", name="validationstatus"
    )
    validation_status_enum.create(op.get_bind())

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'value', name='uq_tags_key_value')
    )
    op.create_table('device_status_cache',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('thermostat_state', sa.String(length=32), nullable=True),
    sa.Column('space_temp', sa.Float(), nullable=True),
    sa.Column('heat_temp', sa.Float(), nullable=True),
    sa.Column('cool_temp', sa.Float(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('device_tags',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'tag_id')
    )
    op.add_column(
        'devices',
        sa.Column(
            'validation_status',
            validation_status_enum,
            nullable=False,
            server_default='PENDING',
        ),
    )
    op.add_column('devices', sa.Column('last_validation_error', sa.String(length=512), nullable=True))
    op.add_column('devices', sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('devices', 'password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('schedule_entries_device_id_fkey'), 'schedule_entries', type_='foreignkey')
    op.create_foreign_key(None, 'schedule_entries', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Downgrades are intentionally unsupported in this project.  If you need
    # to revert a schema change, write a new forward migration that undoes it.
    raise NotImplementedError("downgrade not supported")
